services:
  fast-api:
    build:
      context: .
      dockerfile: Dockerfile.uvicorn
    container_name: uvicorn
    ports:
      - "8000:8000"
    volumes:
      - ./app/uploads:/app/uploads
    networks:
      - webnet
    depends_on:
      - nginx
    restart: always

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./log/nginx:/var/log/nginx
    networks:
      - webnet
    restart: always

networks:
  webnet: